run "ln -nfs #{config.shared_path}/config/settings.yml #{config.release_path}/config/settings.yml"
run "ln -nfs #{config.shared_path}/config/newrelic.yml #{config.release_path}/config/newrelic.yml"
run "ln -nfs #{config.shared_path}/config/s3.yml #{config.release_path}/config/s3.yml"
run "ln -nfs #{config.shared_path}/config/facebooker.yml #{config.release_path}/config/facebooker.yml"
#run "sudo /etc/init.d/memcached restart"
