#!/usr/bin/env ruby
require File.join(File.dirname(__FILE__), '..', 'config', 'environment')
require 'net/imap'
require 'net/http'
require 'rubygems'
require 'logger'

log = Logger.new(STDOUT)

log.info Time.now.to_s + " Warming up to process the clickstream..."

last_clickstream = Clickstream.last_unprocessed.last
clickstreams = Clickstream.unprocessed.all

clickstreams.each do |c|
  log.info "    Processing #{c.clickstreamable_type.to_s} with id #{c.clickstreamable_id.to_s}..."
  unless c.clickstreamable_type.to_s =~ /(?:Home|Session)/i
    object = c.clickstreamable
    if object
      object.viewed = object.viewed ? (object.viewed.to_i + c.cnt.to_i) : c.cnt.to_i
      object.save
    end
  end
end

log.info "    Updating the table as processed below id #{last_clickstream.id}..."

Clickstream.update_all('status=1', "clickstreamable_id is not null and clickstreamable_type is not null and status=0 and id<=#{last_clickstream.id}")

log.info Time.now.to_s + " Done processing clickstream and going to sleep..."